config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "rooms#index"

  get "signup", to: "users#new"

  resource :session
  resources :passwords, param: :token
  resources :users, only: %i[create]
  resources :rooms, only: %i[index new create show] do
    resources :messages, only: %i[create]

    post "join", on: :member
    delete "leave", on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :body, presence: true

  after_create_commit -> { broadcast_prepend_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :sessions, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  normalizes :email, with: ->(e) { e.strip.downcase }

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true

  def avatar_color
    digest = Digest::MD5.hexdigest(name)

    # Use the first 6 characters of the digest as the color code
    color = "##{digest[0..5]}"

    # Output the color code
    color
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      Current.session.present?
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session = find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room

  def create
    message = @room.messages.build(message_params.merge(user: Current.user))
    message.save!
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email: params[:email])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show join leave]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Current.user.rooms.build
  end

  def create
    @room = Current.user.rooms.build(room_params)

    if @room.save
      @room.users << Current.user
      redirect_to @room
    else
      render :new
    end
  end

  def join
    @room.users << Current.user unless @room.users.include?(Current.user)
    redirect_to @room
  end

  def leave
    @room.users.delete(Current.user) if @room.users.include?(Current.user)
    redirect_to @room
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url, notice: "You have been logged in."
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url, notice: "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_authentication, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      start_new_session_for(@user)
      redirect_to root_path, notice: "Welcome!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for_flash_type(type)
    case type
    when "notice" then "bg-blue-50 text-blue-400 border-2 border-blue-100"
    when "alert" then "bg-red-50 text-red-400 border-2 border-red-100"
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "wawa" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="p-4 md:p-6 max-w-screen-xl mx-auto">
      <div class="flex justify-between items-center mb-8">
        <%= link_to root_path do %>
          <%= image_tag "wawa_logo.svg", alt: "Wawa", class: "h-8" %>
        <% end %>

        <div>
          <% if authenticated? %>
            <%= link_to "Sign out", session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign up", signup_path, class: "button button-blue" %>
            <%= link_to "Sign in", new_session_path, class: "button button-blue" %>
          <% end %>
        </div>
      </div>

      <% flash.each do |type, message| %>
        <div class="mb-6 rounded-md flex justify-between items-center px-4 py-3 <%= class_for_flash_type(type) %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="flex gap-x-3">
  <div class="rounded w-10 h-10 flex justify-center items-center text-lg text-white font-medium"
    style="background-color: <%= message.user.avatar_color %>">
    <%= message.user.name.first.upcase %>
  </div>

  <div>
    <div class="space-x-0.5 text-sm">
      <span class="font-medium">
        <%= message.user.name %>
      </span>
      <span class="text-neutral-400">
        <%= time_ago_in_words(message.created_at) %> ago
      </span>
    </div>
    <p>
      <%= message.body %>
    </p>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="grid grid-cols-12 gap-x-8 gap-8">
  <div class="col-span-12 md:col-span-4 lg:col-span-3">
    <%= render "shared/rooms" %>
  </div>

  <div class="col-span-12 md:col-span-8 lg:col-span-9">
    <%= turbo_frame_tag :content do %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<%= turbo_frame_tag "content" do %>
  <h1 class="h1 mb-4">New room</h1>

  <%= form_with model: @room, data: { turbo_frame: "_top" } do |form| %>
    <div class="mb-4 space-y-2">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, required: true, autocorrect: "off", class: "w-full md:w-auto" %>
    </div>

    <%= form.submit "Create room", class: "mt-2 button button-large button-blue w-full md:w-auto" %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<%= content_for :title, @room.name %>

<div class="grid grid-cols-12 gap-8">
  <div class="col-span-12 md:col-span-4 lg:col-span-3">
    <%= render "shared/rooms" %>
  </div>

  <div class="col-span-12 md:col-span-8 lg:col-span-9">
    <%= turbo_frame_tag "content" do %>
      <%= turbo_stream_from @room %>

      <div class="mb-6 rounded-md border-2 border-neutral-100 flex justify-between items-center px-4 py-3">
        <p class="text-neutral-800">
          You're viewing
          <span class="font-semibold">
            #<%= @room.name %>.
          </span>
        </p>

        <% if @room.users.include?(Current.user) %>
          <%= button_to "Leave room",
            leave_room_path(@room),
            data: { turbo_frame: "content" }, method: :delete,
            class: "button button-red button-outline button-small" %>
        <% else %>
          <%= button_to "Join room",
            join_room_path(@room),
            data: { turbo_frame: "content" },
            class: "button button-blue button-small" %>
        <% end %>
      </div>

      <% if @room.users.include?(Current.user) %>
        <div class="mb-6">
          <%= form_with model: [@room, Message.new],
            data: { turbo_frame: "content", controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form|
          %>
            <div class="flex gap-x-3">
              <%= form.text_field :body, class: "flex-1 w-full", placeholder: "Write a message...", data: { reset_form_target: "input" }
              %>
              <%= form.submit "Send", class: "button button-blue" %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="space-y-4" id="messages">
        <%= render @room.messages.includes(:user) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_rooms.html.erb
<div class="rounded-md border-2 border-neutral-100 px-5 py-3 bg-neutral-50 h-fit">
  <%= link_to "＋ New room", new_room_path, data: { turbo_frame: "content" }, class: "mb-2 block text-neutral-900 font-medium" %>

  <div class="flex flex-col gap-y-1.5 tracking-tight">
    <% Room.order(:name).each do |room| %>
      <%= link_to "# #{room.name}", room_path(room), class: "text-neutral-900 #{"font-semibold" if @room == room}" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="h1 mb-4">Sign up</h1>

<%= form_with model: @user do |form| %>
  <div class="mb-4 space-y-2">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, required: true, autofocus: "true", class: "w-full md:w-auto" %>
  </div>

  <div class="mb-4 space-y-2">
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, required: true, minlength: 8, autocomplete: "new-password", class: "w-full md:w-auto" %>
  </div>

  <div class="mb-4 space-y-2">
    <%= form.label :password_confirmation, class: "form-label" %>
    <%= form.password_field :password_confirmation, required: true, minlength: 8, autocomplete: "new-password", class: "w-full md:w-auto" %>
  </div>

  <div class="mb-4 space-y-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, required: true, autocorrect: "off", class: "w-full md:w-auto" %>
  </div>

  <%= form.submit "Sign up", class: "mt-2 button button-large button-blue w-full md:w-auto" %>
<% end %>